/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "category-products-images": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "swadhesi-user-identity-pool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "swadhesi-user-pool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}